/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessPartnershipsRouteImport } from './routes/business-partnerships'
import { Route as SchoolCollaborationsRouteImport } from './routes/school-collaborations'
import { Route as SiwesRouteImport } from './routes/siwes'
import { Route as SiwesSuccessKitRouteImport } from './routes/siwes-success-kit'
import { Route as TechStoreRouteImport } from './routes/tech-store'
import { Route as VirtualSiwesRouteImport } from './routes/virtual-siwes'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPartnershipsRoute = BusinessPartnershipsRouteImport.update({
  id: '/business-partnerships',
  path: '/business-partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolCollaborationsRoute = SchoolCollaborationsRouteImport.update({
  id: '/school-collaborations',
  path: '/school-collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const SiwesRoute = SiwesRouteImport.update({
  id: '/siwes',
  path: '/siwes',
  getParentRoute: () => rootRouteImport,
} as any)
const SiwesSuccessKitRoute = SiwesSuccessKitRouteImport.update({
  id: '/siwes-success-kit',
  path: '/siwes-success-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStoreRoute = TechStoreRouteImport.update({
  id: '/tech-store',
  path: '/tech-store',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualSiwesRoute = VirtualSiwesRouteImport.update({
  id: '/virtual-siwes',
  path: '/virtual-siwes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-partnerships': typeof BusinessPartnershipsRoute
  '/school-collaborations': typeof SchoolCollaborationsRoute
  '/siwes': typeof SiwesRoute
  '/siwes-success-kit': typeof SiwesSuccessKitRoute
  '/tech-store': typeof TechStoreRoute
  '/virtual-siwes': typeof VirtualSiwesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-partnerships': typeof BusinessPartnershipsRoute
  '/school-collaborations': typeof SchoolCollaborationsRoute
  '/siwes': typeof SiwesRoute
  '/siwes-success-kit': typeof SiwesSuccessKitRoute
  '/tech-store': typeof TechStoreRoute
  '/virtual-siwes': typeof VirtualSiwesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-partnerships': typeof BusinessPartnershipsRoute
  '/school-collaborations': typeof SchoolCollaborationsRoute
  '/siwes': typeof SiwesRoute
  '/siwes-success-kit': typeof SiwesSuccessKitRoute
  '/tech-store': typeof TechStoreRoute
  '/virtual-siwes': typeof VirtualSiwesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-partnerships'
    | '/school-collaborations'
    | '/siwes'
    | '/siwes-success-kit'
    | '/tech-store'
    | '/virtual-siwes'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
    | '/blog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-partnerships'
    | '/school-collaborations'
    | '/siwes'
    | '/siwes-success-kit'
    | '/tech-store'
    | '/virtual-siwes'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog'
    | '/events'
    | '/blog/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-partnerships'
    | '/school-collaborations'
    | '/siwes'
    | '/siwes-success-kit'
    | '/tech-store'
    | '/virtual-siwes'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
    | '/blog/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessPartnershipsRoute: typeof BusinessPartnershipsRoute
  SchoolCollaborationsRoute: typeof SchoolCollaborationsRoute
  SiwesRoute: typeof SiwesRoute
  SiwesSuccessKitRoute: typeof SiwesSuccessKitRoute
  TechStoreRoute: typeof TechStoreRoute
  VirtualSiwesRoute: typeof VirtualSiwesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-partnerships': {
      id: '/business-partnerships'
      path: '/business-partnerships'
      fullPath: '/business-partnerships'
      preLoaderRoute: typeof BusinessPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-collaborations': {
      id: '/school-collaborations'
      path: '/school-collaborations'
      fullPath: '/school-collaborations'
      preLoaderRoute: typeof SchoolCollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siwes': {
      id: '/siwes'
      path: '/siwes'
      fullPath: '/siwes'
      preLoaderRoute: typeof SiwesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siwes-success-kit': {
      id: '/siwes-success-kit'
      path: '/siwes-success-kit'
      fullPath: '/siwes-success-kit'
      preLoaderRoute: typeof SiwesSuccessKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-store': {
      id: '/tech-store'
      path: '/tech-store'
      fullPath: '/tech-store'
      preLoaderRoute: typeof TechStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-siwes': {
      id: '/virtual-siwes'
      path: '/virtual-siwes'
      fullPath: '/virtual-siwes'
      preLoaderRoute: typeof VirtualSiwesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessPartnershipsRoute: BusinessPartnershipsRoute,
  SchoolCollaborationsRoute: SchoolCollaborationsRoute,
  SiwesRoute: SiwesRoute,
  SiwesSuccessKitRoute: SiwesSuccessKitRoute,
  TechStoreRoute: TechStoreRoute,
  VirtualSiwesRoute: VirtualSiwesRoute,
  BlogSlugRoute: BlogSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
