INSERT INTO public.talent_roles
(slug, title, role_kind, company, city, country, is_remote, employment_type, summary, description, responsibilities, required_skills, nice_to_have, seniority, budget_min, budget_max, budget_currency, budget_unit, openings, status, is_featured)
VALUES
('marketing-sales-representative', 'Marketing & Sales Representative', 'internal', 'Tech Faculty', 'Nnewi', 'Nigeria', false, 'full_time',
 'Go out to businesses in Nnewi, Onitsha and Awka, open conversations and sign them up for Tech Faculty projects and training.',
 'We are building a pipeline of vetted tech talent ready to solve real problems for Nigerian and African businesses. This role is the front line: you meet business owners, understand what is slowing them down, and bring the work back to our talent pool. Field and phone based, with commission on every signed client.',
 ARRAY['Prospect and visit local businesses, markets and industrial clusters','Explain Tech Faculty services clearly and handle objections','Collect requirements and pass qualified briefs to the project team','Follow up on WhatsApp and close signed agreements','Report weekly on pipeline and conversions'],
 ARRAY['Sales','Marketing','Communication','Customer relationship management','WhatsApp business communication'],
 ARRAY['Experience selling to SMEs','Igbo language fluency','Own smartphone and transport'],
 'entry', 80000, 200000, 'NGN', 'MONTH', 3, 'published', true),
('project-manager-client-acquisition', 'Project Manager (Client Acquisition)', 'internal', 'Tech Faculty', 'Nnewi', 'Nigeria', true, 'full_time',
 'Turn signed business briefs into delivered projects, and match the right talent from our pool to each one.',
 'You own delivery. When a business signs on, you scope the work, assemble a team from the Tech Faculty talent pool, set timelines, and make sure the client gets a result they will refer others for. Hybrid: remote with visits to clients in the South-East.',
 ARRAY['Scope incoming business briefs into clear deliverables','Assemble and brief talent teams for each project','Track timelines, blockers and client communication','Review delivered work before handover','Keep project documentation and reports up to date'],
 ARRAY['Project management','Client communication','Team coordination','Documentation','Agile basics'],
 ARRAY['Technical background','Experience with Notion, Trello or Jira','Prior agency or studio experience'],
 'mid', 150000, 350000, 'NGN', 'MONTH', 2, 'published', true),
('business-development-associate', 'Business Development Associate', 'internal', 'Tech Faculty', 'Lagos', 'Nigeria', true, 'contract',
 'Open doors to medium and large businesses across Nigeria and Africa that need remote tech teams.',
 'A partnership-focused role for someone comfortable pitching companies rather than shops. You build a target list, reach decision makers, and bring signed engagements to our delivery team. Commission-heavy with a base retainer.',
 ARRAY['Build and work a target list of medium and large businesses','Run discovery calls and pitch our talent pool','Negotiate scope and commercial terms','Maintain the CRM and pipeline reporting'],
 ARRAY['Business development','B2B sales','Negotiation','Presentation','Email outreach'],
 ARRAY['Existing network in Nigerian business or tech','LinkedIn outreach experience'],
 'mid', 100000, 400000, 'NGN', 'MONTH', 2, 'published', true),
('full-stack-developer-client-projects', 'Full-Stack Developer (Client Projects)', 'client', 'Tech Faculty Clients', NULL, 'Nigeria', true, 'contract',
 'Build websites, dashboards and internal tools for Nigerian businesses on short remote engagements.',
 'A rolling opening for developers in our talent pool. As client projects come in, we match matching profiles to paid remote engagements — typically two to eight weeks, part or full time. Rates depend on scope and your proven level.',
 ARRAY['Build and ship client web applications','Work to an agreed scope and timeline','Communicate progress to the project manager','Hand over clean, documented work'],
 ARRAY['JavaScript','React','HTML','CSS','Git','APIs'],
 ARRAY['TypeScript','Supabase or Firebase','Tailwind CSS','Node.js'],
 'mid', 150000, 600000, 'NGN', 'MONTH', 5, 'published', true);